### ISSUE TITLE
Consider moving these signalr samples in the Samples repo under a aspnetcore/signalr folder

### ISSUE THREAD

**Issue by danroth27** [aspnet/SignalR-samples#10]
We now have a [Samples](https://github.com/aspnet/samples) repo. Moving these SignalR samples there might make them more discoverable.

**Comment by hannesne** [comment]
Could you perhaps add this repo to that one as a submodule? https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by anurse** [comment]
Given that we've seen some issues reported here, I'd rather keep it separate. Thoughts @davidfowl ?

**Comment by davidfowl** [comment]
I think we should keep them separate as well.
