### ISSUE TITLE
SignalR .Net Core 3.1 unable to send object in SendAsync method from service class

### ISSUE THREAD

**Issue by adzharkahar** [aspnet/SignalR-samples#101]
Previously I was using .Net Core 2.2, I was able to send a json object from a service class using hub context and SendAsync method to a front end web client. Im having issues after I've upgraded my project framework to 3.1. If i call the SendAsync method using a json object, it will hit an error stating "{"The collection type 'Newtonsoft.Json.Linq.JObject' is not supported."}", if I send any other class object it will directly go to OnDisconnected.

Sample of the method i use

**Using Json Object**: await _hubContext.Clients.Group(groupName).SendAsync("NotificationResponse", jsonObject);

**Using Class Object**: await _hubContext.Clients.Group(groupName).SendAsync("NotificationResponse", notificationObject);

I've tried sending object directly from the hub, I was able to send a normal class object but not a json object. I did the testing on my project and also sample from this tutorial: https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio

**Comment by BrennanConroy** [comment]
2.1 was using Newtonsoft internally for Json, 3.1 uses System.Text.Json. If you're using features that don't work with System.Text.Json you can switch back to Newtonsoft https://docs.microsoft.com/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#switch-to-newtonsoftjson

**Comment by adzharkahar** [comment]
that fixed it ! 
thanks a lot !
