### ISSUE TITLE
Transport Fallback for Chat Sample Not Working

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/SignalR-samples#11]
Right now it seems like transport fallback isn't working. Ran into this when publishing an app to Antares with Websockets disabled.

**Comment by mikaelm12** [comment]
Looks like this wasn't actually merged... 
Experimental pr only: https://github.com/aspnet/SignalR-samples/pull/9

**Comment by moozzyk** [comment]
I found an issue with the reconnect part which I haven't had a chance to fix but the main purpose of this PR was to see how hard it is to implement reconnects on your own.
