### ISSUE TITLE
NodeClient in the example, the NodeClient client connects to the hub port error 

### ISSUE THREAD

**Issue by sgalcheung** [aspnet/SignalR-samples#110]
In the example, the NodeClient client connects to the hub port error 
https://github.com/aspnet/SignalR-samples/blob/21ef2891cce548b64c5c9ddc7c0f437c521a5bd4/StockTickR/NodeClient/app.js#L4

Should be 5000

**Comment by sgalcheung** [comment]
#111

**Comment by BrennanConroy** [comment]
Closed via https://github.com/aspnet/SignalR-samples/pull/111
