### ISSUE TITLE
CSharpClient Not Working

### ISSUE THREAD

**Issue by daveoggy** [aspnet/SignalR-samples#16]
I can run the StockTickRApp and connect the NodeClient and see stock prices written to the console. When I connect the CSharpClient it does not write anything to the console.

From debugging I suspect this section:
```
var state = await connection.InvokeAsync<string>("GetMarketState");
if (string.Equals(state, "Open"))
```
The call to GetMarketState returns "Closed" so the StartStreaming method is never called.

**Comment by BrennanConroy** [comment]
If you connect to the server via the browser and click the `Open Market` button then the CSharpClient should start streaming stocks

**Comment by daveoggy** [comment]
Thanks, that works.
