### ISSUE TITLE
Could you update to preview2?

### ISSUE THREAD

**Issue by kevin-jing** [aspnet/SignalR-samples#22]
ChatSample works, but if I update Microsoft.AspNetCore.All from preview1 to preview2, it doesn't work. So, could you provide an example using preview2?

**Comment by mikaelm12** [comment]
Hey @kevin-jing The chat sample is now updated to to preview 2.
Just to give you a heads up on what I had to change to update it. I had to update both the client side version from NPM to preview2 and the server side package from nuget to preview2.
We also renamed the aspnetcore.signalr.sockets project so I had to fix that reference as well.

Hope this helps!

**Comment by mikaelm12** [comment]
The start logic was also simplified since transport fallback is built into start in preview2 but that's **not** a breaking change

**Comment by mikaelm12** [comment]
Done in: d154f53e741b98fac5d5bf000c60bbbd90061a6d
