### ISSUE TITLE
How to use ClientWebSocket to connect to SignalR Server

### ISSUE THREAD

**Issue by LGinC** [aspnet/SignalR-samples#33]
How to do it

**Comment by davidfowl** [comment]
What exactly are you trying to accomplish? You basically need to write and read the HubProtocol yourself (see https://github.com/aspnet/SignalR/blob/dev/specs/HubProtocol.md)

**Comment by LGinC** [comment]
@davidfowl I want to use WechatMiniProgram's websocket client connect to my SignalR Server. Connect failed because of a protocol in WechatMiniProgram's websocket 
`WebSocket connection to 'wss://myhost/signalr' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received`

**Comment by davidfowl** [comment]
> @davidfowl I want to use WechatMiniProgram's websocket client connect to my SignalR Server. Connect failed because of a protocol in WechatMiniProgram's websocket

Why not use the regular SignalR client? What's special about the WechatMiniProgram's websocket library?

**Comment by LGinC** [comment]
@davidfowl yes, there is just a websocket client in WechatMiniProgram

**Comment by davidfowl** [comment]
I'm suspicious that this will even work. It seems like the websocket client is using subprotocols (in this case protocol1, whatever that is). You can set the subprotocol on the server side with something like this:

```C#
app.UseSignalR(routes =>
{
    routes.MapHub<AppHub>("/app", options =>
    {
        options.WebSockets.SubProtocolSelector = requestedProtocols =>
        {
            return requestedProtocols.Count > 0 ? requestedProtocols[0] : null;
        };
    });
});
```

The code above will select the first of the requested subprotocols in the list. You can try that and see if you make any progress

**Comment by LGinC** [comment]
@davidfowl 
![image](https://user-images.githubusercontent.com/15363011/40219602-aa5a6fa8-5aa8-11e8-8d9d-e50168bc6c82.png)
.net core signalr
there is no member called SubProtocolSelector

**Comment by LGinC** [comment]
@davidfowl
cool, let SubProtocol = "protocol1", and connect success.

**Comment by LGinC** [comment]
@davidfowl oh.....
![image](https://user-images.githubusercontent.com/15363011/40220045-5c8c70a8-5aaa-11e8-9f71-504c46a9b2b3.png)
What Happened? I can't send message

**Comment by davidfowl** [comment]
> there is no member called SubProtocolSelector

You're using 1.0.0-preview2-final, the newest version is 1.0.0-rc1-final and the API has changed.

> What Happened? I can't send message

SignalR has a protocol and it looks like the wechat websocket client you are using has it's own protocol that is incompatible so it will not work.

**Comment by LGinC** [comment]
@davidfowl 

![tim 20180518153247](https://user-images.githubusercontent.com/15363011/40222033-c453e3b4-5ab0-11e8-9c8d-5a9a20369104.png)
I use the ClientWebSocket to connect my server.

![image](https://user-images.githubusercontent.com/15363011/40222064-dc22d054-5ab0-11e8-94a4-72b1dd14aa82.png)


but it disconnect when I send message
![image](https://user-images.githubusercontent.com/15363011/40222099-0097eca8-5ab1-11e8-82c5-ac23de645886.png)

**Comment by davidfowl** [comment]
Please read the hub protocol specification outlined here https://github.com/aspnet/SignalR/blob/dev/specs/HubProtocol.md. This is what you need to implement to use Hubs.

**Comment by LGinC** [comment]
@davidfowl I find the confing in function ConfigureServices in startup.cs
`services.AddSignalR(options =>
            {
                // Faster pings for testing
                options.KeepAliveInterval = TimeSpan.FromSeconds(5);
            }).AddJsonProtocol(options =>
            {
                //options.PayloadSerializerSettings.Converters.Add(JsonConver);
                //the next settings are important in order to serialize and deserialize date times as is and not convert time zones
                options.PayloadSerializerSettings.Converters.Add(new IsoDateTimeConverter());
                options.PayloadSerializerSettings.DateTimeZoneHandling = DateTimeZoneHandling.Unspecified;
                options.PayloadSerializerSettings.DateParseHandling = DateParseHandling.DateTimeOffset;
            });`

and client send handshakeRequest   
`{
"protocol": "json",
"version": 1
}`



but server cannot parse the request 

ERROR 2018-05-22 10:40:38,635 [3    ] oft.AspNetCore.Sockets.ConnectionManager - Failed disposing connection a4589209-d77e-408e-b54d-0efd29dc4a79.
System.IO.InvalidDataException: Unable to parse payload as a negotiation message.
   at Microsoft.AspNetCore.SignalR.Internal.Protocol.NegotiationProtocol.TryParseMessage(ReadOnlySpan`1 input, NegotiationMessage& negotiationMessage)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.<NegotiateAsync>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.HubEndPoint`1.<OnConnectedAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by LGinC** [comment]
resolve it in [this](https://github.com/aspnet/SignalR/issues/2331#issuecomment-390851864)
