### ISSUE TITLE
Signalr Java client for android not working

### ISSUE THREAD

**Issue by Abianue1** [aspnet/SignalR-samples#50]

**Comment by Abianue1** [comment]
Hi, Sorry about that. i was going to send more information before i hi send.

I have been trying to working with signalr and a java client ever since the announcement  this month.

I am using the android javaclient sample project from here https://github.com/aspnet/SignalR-samples/tree/master/AndroidJavaClient

Firstly, the signalr library in the project is 
 implementation 'com.microsoft.aspnet:signalr:0.1.0-preview1-35029'
but i found another version 
 implementation 'com.microsoft.aspnet:signalr:0.1.0-preview2-35174'

But regardless, none of them work
i am getting this error
9-30 09:33:54.732 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: android.os.NetworkOnMainThreadException
09-30 09:33:54.738 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1450)
09-30 09:33:54.743 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:102)
09-30 09:33:54.748 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
09-30 09:33:54.753 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:787)
09-30 09:33:54.755 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.Dns$1.lookup(Dns.java:40)
09-30 09:33:54.759 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
09-30 09:33:54.762 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
09-30 09:33:54.765 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
09-30 09:33:54.769 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
09-30 09:33:54.773 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
09-30 09:33:54.776 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
09-30 09:33:54.780 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
09-30 09:33:54.783 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-30 09:33:54.787 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-30 09:33:54.790 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
09-30 09:33:54.793 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-30 09:33:54.796 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-30 09:33:54.798 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
09-30 09:33:54.801 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-30 09:33:54.804 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
09-30 09:33:54.807 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
09-30 09:33:54.809 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
09-30 09:33:54.812 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
09-30 09:33:54.814 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at okhttp3.RealCall.execute(RealCall.java:77)
09-30 09:33:54.817 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at com.microsoft.aspnet.signalr.Negotiate.processNegotiate(Negotiate.java:33)
09-30 09:33:54.819 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at com.microsoft.aspnet.signalr.HubConnection.start(HubConnection.java:167)
09-30 09:33:54.821 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at com.microsoft.aspnet.signalr.samples.androidjavaclient.MainActivity.onCreate(MainActivity.java:62)
09-30 09:33:54.822 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.Activity.performCreate(Activity.java:7253)
09-30 09:33:54.823 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.Activity.performCreate(Activity.java:7244)
09-30 09:33:54.825 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
09-30 09:33:54.826 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2774)
09-30 09:33:54.827 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2899)
09-30 09:33:54.828 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
09-30 09:33:54.829 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1625)
09-30 09:33:54.830 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
09-30 09:33:54.831 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.os.Looper.loop(Looper.java:164)
09-30 09:33:54.832 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6558)
09-30 09:33:54.833 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-30 09:33:54.834 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
09-30 09:33:54.835 10808-10808/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)


I am not sure want the error is because there is no message i error.
I only have the stack trace.

Thanks

**Comment by BrennanConroy** [comment]
Looks like a simple fix https://stackoverflow.com/questions/22395417/error-strictmodeandroidblockguardpolicy-onnetwork

@mikaelm12 We should update the sample and figure out why this wasn't happening when running the sample ourselves.

**Comment by mikaelm12** [comment]
Ah no. That's not the correct solution. I have an updated sample that uses Android' [Async Task](https://developer.android.com/reference/android/os/AsyncTask) which is how you should be doing network calls. I'll update the official sample

**Comment by Abianue1** [comment]
@BrennanConroy Thanks for the tip. I proceed to use your suggestion as a work around for now until @mikaelm12 updates the offical sample.

However, i am getting a new error regardless even after apply the work around of 

`   @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
        StrictMode.setThreadPolicy(policy);

        setContentView(R.layout.activity_main);
        HubConnection hubConnection = new HubConnection("http://sandbjoukbox.azurewebsites.net/notification");
        TextView textView = (TextView)findViewById(R.id.tvMain);
        ListView listView = (ListView)findViewById(R.id.lvMessages);
        Button sendButton = (Button)findViewById(R.id.bSend);
        EditText editText = (EditText)findViewById(R.id.etMessageText);

        List<String> messageList = new ArrayList<String>();
        ArrayAdapter<String> arrayAdapter = new ArrayAdapter<String>(MainActivity.this,
                android.R.layout.simple_list_item_1, messageList);
        listView.setAdapter(arrayAdapter);

        hubConnection.on("echo", (message)-> {
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    arrayAdapter.add(message);
                    arrayAdapter.notifyDataSetChanged();
                }
            });
        }, String.class);

        sendButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                String message = editText.getText().toString();
                editText.setText("");
                try {
                    hubConnection.send("echo", message);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

        try {
            hubConnection.start();
        } catch (Exception e) {
            e.printStackTrace();
            textView.setText("There was an error: " + e.getMessage());
        }
    }`
Stacke Trace
9-30 21:52:03.056 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: java.lang.Exception: There was an error starting the Websockets transport.
09-30 21:52:03.060 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at com.microsoft.aspnet.signalr.WebSocketTransport.start(WebSocketTransport.java:58)
09-30 21:52:03.063 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at com.microsoft.aspnet.signalr.HubConnection.start(HubConnection.java:198)
09-30 21:52:03.067 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at com.microsoft.aspnet.signalr.samples.androidjavaclient.MainActivity.onCreate(MainActivity.java:66)
09-30 21:52:03.070 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.Activity.performCreate(Activity.java:7253)
09-30 21:52:03.073 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.Activity.performCreate(Activity.java:7244)
09-30 21:52:03.076 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
09-30 21:52:03.080 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2774)
09-30 21:52:03.083 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2899)
09-30 21:52:03.085 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
09-30 21:52:03.088 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1625)
09-30 21:52:03.092 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
09-30 21:52:03.094 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.os.Looper.loop(Looper.java:164)
09-30 21:52:03.096 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6558)
09-30 21:52:03.098 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-30 21:52:03.101 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
09-30 21:52:03.103 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

**Comment by Abianue1** [comment]
@BrennanConroy Thanks for the tip. I proceed to use your suggestion as a work around for now until @mikaelm12 updates the offical sample.

However, i am getting a new error regardless even after apply the work around of

` @override
protected void onCreate(Bundle savedInstanceState) {
super.onCreate(savedInstanceState);
StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
StrictMode.setThreadPolicy(policy);

    setContentView(R.layout.activity_main);
    HubConnection hubConnection = new HubConnection("test@test.com");
    TextView textView = (TextView)findViewById(R.id.tvMain);
    ListView listView = (ListView)findViewById(R.id.lvMessages);
    Button sendButton = (Button)findViewById(R.id.bSend);
    EditText editText = (EditText)findViewById(R.id.etMessageText);

    List<String> messageList = new ArrayList<String>();
    ArrayAdapter<String> arrayAdapter = new ArrayAdapter<String>(MainActivity.this,
            android.R.layout.simple_list_item_1, messageList);
    listView.setAdapter(arrayAdapter);

    hubConnection.on("echo", (message)-> {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                arrayAdapter.add(message);
                arrayAdapter.notifyDataSetChanged();
            }
        });
    }, String.class);

    sendButton.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View view) {
            String message = editText.getText().toString();
            editText.setText("");
            try {
                hubConnection.send("echo", message);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    });

    try {
        hubConnection.start();
    } catch (Exception e) {
        e.printStackTrace();
        textView.setText("There was an error: " + e.getMessage());
    }
}`
Stacke Trace
9-30 21:52:03.056 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: java.lang.Exception: There was an error starting the Websockets transport.
09-30 21:52:03.060 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at com.microsoft.aspnet.signalr.WebSocketTransport.start(WebSocketTransport.java:58)
09-30 21:52:03.063 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at com.microsoft.aspnet.signalr.HubConnection.start(HubConnection.java:198)
09-30 21:52:03.067 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at com.microsoft.aspnet.signalr.samples.androidjavaclient.MainActivity.onCreate(MainActivity.java:66)
09-30 21:52:03.070 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at android.app.Activity.performCreate(Activity.java:7253)
09-30 21:52:03.073 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at android.app.Activity.performCreate(Activity.java:7244)
09-30 21:52:03.076 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
09-30 21:52:03.080 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2774)
09-30 21:52:03.083 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2899)
09-30 21:52:03.085 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at android.app.ActivityThread.-wrap11(Unknown Source:0)
09-30 21:52:03.088 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1625)
09-30 21:52:03.092 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at android.os.Handler.dispatchMessage(Handler.java:106)
09-30 21:52:03.094 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at android.os.Looper.loop(Looper.java:164)
09-30 21:52:03.096 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at android.app.ActivityThread.main(ActivityThread.java:6558)
09-30 21:52:03.098 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at java.lang.reflect.Method.invoke(Native Method)
09-30 21:52:03.101 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
09-30 21:52:03.103 27162-27162/com.microsoft.aspnet.signalr.samples.androidjavaclient W/System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

**Comment by mikaelm12** [comment]
The new issue might have to do with the fact that you're trying to connect to "test@test.com". Try hitting a real SignalR server endpoint 😄

**Comment by Abianue1** [comment]
haha. no. i didnt want to put my offical url here? i would like to believe i am smarter than that.
Thanks

**Comment by mikaelm12** [comment]
It looks like the client's call to connect in the Websockets transport  is failing. Can you confirm that websockets are enabled on your endpoint?

**Comment by mikaelm12** [comment]
This can go by unnoticed with other clients because they have transport fallback enabled.

**Comment by mikaelm12** [comment]
Great. Glad that worked for you @Abianue1 . 
Yeah in the C# and TypeScript client we have transport fallback so even if you don't have Websockets enabled you'll still be able to connect with SSE or LongPolling no problem. In the Java client we only support Websockets currently, but when we add support for more transports we'll be able to add the fallback feature there as well. 
Anyways, glad you got it working!

**Comment by anurse** [comment]
It looks like the main issue is resolved. @mikaelm12 if you want to update the sample to use Async Task, feel free to file an issue for that and do it :)

**Comment by sathishmscict** [comment]
what is minSdkVersion which support new-signalr-client. In sample app mentioned minSdkVersion:26 .Is it support only from api level 26.

**Comment by mirzamudassar** [comment]
com.microsoft.aspnet.signalr.HubException: There were no compatible transports on the server
at com.microsoft.aspnet.signalr.HubConnection.start(HubConnection.java:188)

**Comment by anurse** [comment]
Please open an issue on https://github.com/aspnet/AspNetCore with your report/question. This repository is not actively monitored.

**Comment by mirzamudassar** [comment]
> Please open an issue on https://github.com/aspnet/AspNetCore with your report/question. This repository is not actively monitored for product-related questions/issues.

i face this issue in android end...is this issue in on server side?

**Comment by mikaelm12** [comment]
The error message indicated that the transport selected on the client side isn't available on the server. The default transport is websockets but cloud providers generally default to having webosckets not enabled. You should try to verify that you have webosckets enabled on the server side, or you can opt to use the LongPolling transport on the client.

**Comment by anurse** [comment]
> i face this issue in android end...is this issue in on server side?

Both client and server-side issues are tracked at aspnet/AspNetCore.
