### ISSUE TITLE
About network changes

### ISSUE THREAD

**Issue by xiazunyang** [aspnet/SignalR-samples#58]
https://github.com/aspnet/SignalR/blob/master/clients/java/signalr/src/main/java/com/microsoft/signalr/OkHttpWebSocketWrapper.java 

line 98.

``` onClose.invoke(null, t.getMessage());```Should be changed to``` onClose.accept(0, t.getMessage());```

Otherwise a NullPointerException is reported when the network state changes.

**Comment by BrennanConroy** [comment]
Closing as you filed the same issue on the aspnet/signalr repo.
