### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by ogomaemmanuel** [aspnet/SignalR-samples#59]
would please add bearer token authentication sample

**Comment by bradygaster** [comment]
Have you seen either one of these samples in the main repository? (Seems like we should move the samples into their own place - I'll take that action item!)

https://github.com/aspnet/AspNetCore/tree/master/src/SignalR/samples/JwtClientSample
https://github.com/aspnet/AspNetCore/tree/master/src/SignalR/samples/JwtSample
