### ISSUE TITLE
Can i use bare EventSource() Sever Sent Event, to connect signalr hub ?

### ISSUE THREAD

**Issue by leung85** [aspnet/SignalR-samples#96]
Can i use bare js EventSource() Sever Sent Event, to connect signalr hub ?

If not , how to use sse with signalr ?

**Comment by BrennanConroy** [comment]
> Can i use bare js EventSource() Sever Sent Event, to connect signalr hub ?

No, SignalR is a library with a protocol and the library will fallback to SSE internally if it can't use WebSockets.

If you want to use base EventSource for some reason, you'll need to read the SignalR protocol spec and implement the protocol yourself. https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/TransportProtocols.md and https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/docs/specs/HubProtocol.md
